version: "2"
services:
  new-easyepg:
    image: takealug/new-easyepg:latest
    container_name: new-easyepg
    environment:
      - PUID=99
      - PGID=100
      - TIMEZONE=Europe/Berlin
      - UPDATE=yes
      - REPO=script.service.easyepg-lite
      - BRANCH=main
    volumes:
      - /home/dockeruser/new-easyepg/data:/easyepg
      - /home/dockeruser/new-easyepg/xml:/easyepg/xml
    tmpfs:
      - /var/log
      - /tmp
    ports:
      - 4000:4000
    restart: unless-stopped