#!/bin/bash
# downloads a local copy of qemu on docker-hub build machines
curl -L https://github.com/balena-io/qemu/releases/download/v7.0.0%2Bbalena1/qemu-7.0.0.balena1-arm.tar.gz | tar zxvf - -C . && mv qemu-7.0.0+balena1-arm/qemu-arm-static root/qemu-arm-static
curl -L https://github.com/balena-io/qemu/releases/download/v7.0.0%2Bbalena1/qemu-7.0.0.balena1-aarch64.tar.gz | tar zxvf - -C . && mv qemu-7.0.0+balena1-aarch64/qemu-aarch64-static root/qemu-aarch64-static